### ISSUE TITLE
[BUG] "Details"

### ISSUE THREAD

**Issue by Neeksman** [Althro/Tinvaak2#7]
**Upload your crashlog**

If you've crashed, upload your crashlog from `Overwrite\NetScriptFramework`. Reports of crashes that do not include a crashlog will be **ignored and closed.**
[Crash_2021_11_6_10-30-0.txt](https://github.com/Althro/Tinvaak2/files/7491012/Crash_2021_11_6_10-30-0.txt)

**Required: Modlist.txt**
[modlist.txt](https://github.com/Althro/Tinvaak2/files/7491024/modlist.txt)

You must also include your modlist.txt from `F:\Tinvaak\profiles\Tinvaak`

**Describe the bug**
A clear and concise description of what the bug is. Failure to do this will result in the report being **closed and ignored.**
So when I wait for the mods to load as I just start a new playthrough, and then I make a new character, and then press continue it gets to a loading screen where I suppose It is putting me into the world, but then CTD.

**To Reproduce**

1. Go to '...' Last menu after typing and accepting characters name when creating character
2. Do '...' Press continue and wait for mod list (note that it usually says engarde is starting)

**Expected behavior**
Once you press continue instead of reloading gear, the screen will begin to fade to black into a loading screen, however after a few seconds, you get a CTD

**Screenshots**
If applicable, add screenshots to help explain your problem. I highly recommend opening the console and clicking on the object that has a bug. If your bug is location based, use the book from [Where in Special Edition am I](https://www.nexusmods.com/skyrimspecialedition/mods/30907) mod.
N/A

**Modlist version**
2.0
**Did you add any additional mods?**
NO
***YOU MUST DECLARE IF YOU HAVE MODIFIED THE LIST.***

**Comment by Althro** [comment]
From reading that crashlog, it appears that your pagefile is not big enough. Please increase your pagefile by doing the following:

1. Press Windows + R on your keyboard and enter sysdm.cpl ,3
2. Under the Performance section, press 'Settings'
3. Go to the Advanced tab at the top, and at the Virtual memory section press 'Change...'
4. Disable 'Automatically manage paging file size for all drives'
5. If you have more than one drive, try enabling it for at least one more drive as a backup (make sure it has a decent bit of free space, like 15GB). Set the size to 'System managed size'.
Otherwise, set a custom size for the drive it's currently on and increase the maximum size to be at least 20GB.

**Comment by Neeksman** [comment]
Thank you very much!!!
